Bomberman
Tourmi/Retro-ML pull request #74
Opened 2022-08-01 17:59 UTC by Jaewongtongsoup

Bomberman implementation

2022-08-01 22:01 UTC, Tourmi requested changes

2022-08-01 22:01 UTC, Tourmi commented on Retro_ML_TEST/Game/SuperBomberman3/DataFetcherTest.cs
> +    }
MathUtils has the exact same function, please use that one instead.

2022-08-01 22:01 UTC, Tourmi commented on Retro_ML_TEST/Retro_ML_TEST.csproj
>      <ProjectReference Include="..\Retro_ML\Retro_ML.csproj" />
```suggestion
    <ProjectReference Include="..\Games\Retro_ML.Metroid\Retro_ML.Metroid.csproj" />
    <ProjectReference Include="..\Games\Retro_ML.SuperBomberman3\Retro_ML.SuperBomberman3.csproj" />
    <ProjectReference Include="..\Retro_ML\Retro_ML.csproj" />
```

2022-08-02 14:24 UTC, Jaewongtongsoup commented on Games/Retro_ML.SuperBomberman3/Game/SB3DataFetcher.cs
> +        /// Useful to keep track of the bombs that are being planted on the map but needs to be called for every frames.
Resolved

2022-08-02 14:25 UTC, Jaewongtongsoup commented on Retro-ML.sln
>  	EndProjectSection
Resolved

2022-08-02 15:57 UTC, Tourmi approved these changes

2022-08-02 15:57 UTC, merged